# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: bot.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\tbot.proto\"\x1b\n\x0bPlayerState\x12\x0c\n\x04time\x18\x10 \x01(\x05\"#\n\x03\x42ot\x12\x1c\n\x06states\x18\x02 \x03(\x0b\x32\x0c.PlayerState')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'bot_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _PLAYERSTATE._serialized_start=13
  _PLAYERSTATE._serialized_end=40
  _BOT._serialized_start=42
  _BOT._serialized_end=77
# @@protoc_insertion_point(module_scope)
